-- Update movie descriptions
UPDATE movies SET description = 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.' WHERE movie_id = 1; -- Inception
UPDATE movies SET description = 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.' WHERE movie_id = 2; -- La La Land
UPDATE movies SET description = 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.' WHERE movie_id = 3; -- Fight Club
UPDATE movies SET description = 'A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.' WHERE movie_id = 4; -- Shrek
UPDATE movies SET description = 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.' WHERE movie_id = 5; -- The Godfather
UPDATE movies SET description = 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.' WHERE movie_id = 6; -- Oppenheimer
UPDATE movies SET description = 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.' WHERE movie_id = 7; -- The Dark Knight
UPDATE movies SET description = 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.' WHERE movie_id = 8; -- Forrest Gump
UPDATE movies SET description = 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.' WHERE movie_id = 9; -- The Matrix
UPDATE movies SET description = 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.' WHERE movie_id = 10; -- Gladiator
UPDATE movies SET description = 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.' WHERE movie_id = 11; -- Parasite
UPDATE movies SET description = 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.' WHERE movie_id = 12; -- The Social Network
UPDATE movies SET description = 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.' WHERE movie_id = 13; -- The Wolf of Wall Street
UPDATE movies SET description = 'A concierge at a prestigious European hotel becomes the prime suspect in a murder investigation while trying to prove his innocence with the help of a trusted lobby boy.' WHERE movie_id = 14; -- The Grand Budapest Hotel
UPDATE movies SET description = 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.' WHERE movie_id = 15; -- Whiplash
UPDATE movies SET description = 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.' WHERE movie_id = 16; -- Interstellar
UPDATE movies SET description = 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.' WHERE movie_id = 17; -- The Shawshank Redemption
UPDATE movies SET description = 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.' WHERE movie_id = 18; -- The Green Mile
UPDATE movies SET description = 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.' WHERE movie_id = 19; -- Django Unchained
UPDATE movies SET description = 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.' WHERE movie_id = 20; -- Se7en
UPDATE movies SET description = 'A committed dancer struggles to maintain her sanity after winning the lead role in a production of Tchaikovsky\'s "Swan Lake".' WHERE movie_id = 21; -- Black Swan
UPDATE movies SET description = 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.' WHERE movie_id = 22; -- The Revenant
UPDATE movies SET description = 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.' WHERE movie_id = 23; -- Everything Everywhere All At Once
UPDATE movies SET description = 'A Korean family starts a farm in 1980s Arkansas.' WHERE movie_id = 24; -- Minari
UPDATE movies SET description = 'After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.' WHERE movie_id = 25; -- Soul

-- Update series descriptions
UPDATE series SET description = 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.' WHERE series_id = 1; -- Breaking Bad
UPDATE series SET description = 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.' WHERE series_id = 2; -- Stranger Things
UPDATE series SET description = 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.' WHERE series_id = 3; -- Dark
UPDATE series SET description = 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.' WHERE series_id = 4; -- Friends
UPDATE series SET description = 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.' WHERE series_id = 5; -- The Office
UPDATE series SET description = 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.' WHERE series_id = 6; -- Game of Thrones
UPDATE series SET description = 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.' WHERE series_id = 7; -- The Crown
UPDATE series SET description = 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.' WHERE series_id = 8; -- Sherlock
UPDATE series SET description = 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.' WHERE series_id = 9; -- The Witcher
UPDATE series SET description = 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.' WHERE series_id = 10; -- House of Cards
UPDATE series SET description = 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.' WHERE series_id = 11; -- Peaky Blinders
UPDATE series SET description = 'A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.' WHERE series_id = 12; -- How I Met Your Mother
UPDATE series SET description = 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.' WHERE series_id = 13; -- The Mandalorian
UPDATE series SET description = 'Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD\'s 99th Precinct.' WHERE series_id = 14; -- Brooklyn Nine-Nine
UPDATE series SET description = 'The trials and tribulations of criminal lawyer Jimmy McGill in the time before he established his strip-mall law office in Albuquerque, New Mexico.' WHERE series_id = 15; -- Better Call Saul
UPDATE series SET description = 'Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA. But child stardom comes at a price.' WHERE series_id = 16; -- The Queen's Gambit
UPDATE series SET description = 'Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.' WHERE series_id = 17; -- Lupin
UPDATE series SET description = 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.' WHERE series_id = 18; -- Black Mirror
UPDATE series SET description = 'BoJack Horseman was the star of the hit television show "Horsin\' Around" in the \'90s, now he\'s washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.' WHERE series_id = 19; -- BoJack Horseman
UPDATE series SET description = 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.' WHERE series_id = 20; -- The Boys
UPDATE series SET description = 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.' WHERE series_id = 21; -- Rick and Morty
UPDATE series SET description = 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.' WHERE series_id = 22; -- Money Heist
UPDATE series SET description = 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.' WHERE series_id = 23; -- Narcos
UPDATE series SET description = 'Follows Wednesday Addams\' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.' WHERE series_id = 24; -- Wednesday
UPDATE series SET description = 'A family of former child heroes, now grown apart, must reunite to continue to protect the world.' WHERE series_id = 25; -- The Umbrella Academy
